name: 'Reporting a problem'
description: 'Issue to report a problem or bug'
title: 'Problem: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to improve our project! Please fill out the following information:

  - type: textarea
    id: terminal-error
    attributes:
      label: Error from terminal
      description: |
        ```bash
        File: test/index.html
          Config file: index.js
          8:3  error  The <section> element must contain a heading of any level.  expa/section-has-heading  
          ✖ 1 problem (1 error, 0 warning)
        ```
  - type: textarea
    id: example
    attributes:
      label: Part of the code where the error occurred. What configuration was used
      description: |
        ```html
        <section>
          <h1>Title</h1>
        </section>
        ```

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: Please describe the problem or bug in detail. Describe how to reproduce the bug
